[target.xtensa-esp32-espidf]
linker = "ldproxy"
runner = "espflash flash --partition-table partitions.csv --monitor"
rustflags = ["--cfg", "espidf_time64"]

[build]
target = "xtensa-esp32-espidf"

[env]
ESP_IDF_VERSION = "v5.3.3"
ESP_LOG = "info"
ESP_IDF_SDKCONFIG_DEFAULTS = { value = "sdkconfig.defaults", relative = true }

[unstable]
build-std = ["std", "panic_abort"]
